### ISSUE TITLE
Bunched up particles on the edges

### ISSUE THREAD

**Issue by darthmaim** [C-o-d-e-C-o-w-b-o-y/react-snow-overlay#1]
Whenever the snow changes direction, there are a bunch of particles bunched up on the edge. This is especially noticeable with high particle counts, but also happens with smaller numbers (you can see it happening in the video in the README).

https://github.com/user-attachments/assets/35ecb350-cb57-434e-b372-8299f252acac

**Comment by C-o-d-e-C-o-w-b-o-y** [comment]
Thanks for flagging @darthmaim! Will aim to fix shortly

**Comment by C-o-d-e-C-o-w-b-o-y** [comment]
This has now been fixed in the latest version

https://github.com/user-attachments/assets/6441ae01-e05e-4a2e-b3c9-c8579712df26
