### ISSUE TITLE
react 19 fails

### ISSUE THREAD

**Issue by bugzpodder** [C-o-d-e-C-o-w-b-o-y/react-snow-overlay#2]
TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')

**Comment by C-o-d-e-C-o-w-b-o-y** [comment]
Thanks for raising!! Will fix

**Comment by C-o-d-e-C-o-w-b-o-y** [comment]
Hey @bugzpodder, a big thank you for this report

I found out `react-snow-overlay` was unintentionally bundling a verison`react/jsx-runtime`. Removing this has fixed it for React 19, and also greatly reduced the bundle size - so thanks!!

This fix has now been published to npm

Here is a working sandbox demo of React 19 + `react-snow-overlay`: https://codesandbox.io/p/sandbox/jfs4gt?file=%2Fpackage.json%3A15%2C30
