### ISSUE TITLE
Next.js "use client" issue

### ISSUE THREAD

**Issue by jake8655** [C-o-d-e-C-o-w-b-o-y/react-snow-overlay#3]
## Problem
When the component is rendered in an RSC in next, the following error is raised:
```
TypeError: useRef only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/react-client-hook-in-server-component
```

## Solution
I'm pretty sure this happens because in the `index.ts` the component is re-exported without `"use client"` at the top of the file, even though `"use client"` is present in `SnowOverlay.tsx`
https://github.com/C-o-d-e-C-o-w-b-o-y/react-snow-overlay/blob/dd4bb1f9482c055e9b2bbccfc573d9074071c4ba/packages/react-snow-overlay/index.ts#L1
A `"use client"` directive should be added to the `index.ts` file (maybe it also needs to be renamed to tsx then idk)

### Note
It is currently bypass-able if the `SnowOverlay` component is wrapped in a client component and the wrapper is used in the RSC.
```tsx
"use client";

import { SnowOverlay } from "react-snow-overlay";

export default function SnowOverlayWrapper() {
  return <SnowOverlay />;
}

```
_I am willing to open a PR if approved_

**Comment by C-o-d-e-C-o-w-b-o-y** [comment]
Thanks, this is now fixed in version v`1.0.11` 

https://github.com/C-o-d-e-C-o-w-b-o-y/react-snow-overlay/commit/3e3dce7308478bc43a2fa30e2b8fbb5fddb5722d
